spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: PostgreSQL
  jpa:
    hibernate:
      ddl-auto: create
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.metrics.export.influx.InfluxMetricsExportAutoConfiguration